id: A1EC06777
title: Prayer of Aspiration
type: translation
pechas:
- IC3DD04E5
- I468545EC
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:07:20.329476
  last_modified_at: 2023-01-04 12:07:20.329482
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IC3DD04E5/B7FB: F6F0
  I468545EC/54EB: F6F0
